apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.0.0-rc2

patchesStrategicMerge:
- configmap-patch.yaml

images:
- name: ghcr.io/dexidp/dex
  newName: ghcr.io/dexidp/dex
  newTag: v2.27.0
- name: quay.io/argoproj/argocd
  newName: quay.io/argoproj/argocd
  newTag: release-2.0
- name: haproxy
  newName: haproxy
  newTag: 2.0.21-alpine
- name: redis
  newName: redis
  newTag: 6.2.1-alpine
