apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "p0Zc6sgOOL/AVOYBeqxfjTPn/2LwbNMoSc+jBe5wtrkLRbMsfMqduM1WDDGAJu+8\n1KmmXKFKjqYluaNM6jR3IlVE/MUqnCiyBKxDr5fz9GyOzSXrp3qAQX0o71144Fav\nkT/NSMpMffuQA5+RVUmFyx0oc6N7B07z++NA2Y72HYk="
